### PR TITLE
Avoid Expression Error in the info.zpt template

### PR DESCRIPTION
**Pull request by cleberjsantos**
**ExpressionError: Not a valid path-expression.**

```
 - String:     "info_d/?k"
 - Filename:   manage_workspace

 - Expression: "info_d/?k"
 - Filename:   manage_workspace
 - Location:   (0:1338)
 - Arguments:  repeat: {...} (0)

```

### CODE REVIEW

**Comment by jordic** [comment]
Found same bug! 
It appears when switched to five.pt and chameleon templates... @tseaver  
(Seems like it don't likes the info_d/?k)
path traverser. Can we fix it? Should I send a new and updated PR?

**Comment by cleberjsantos** [comment]
@jordic I have a fix here:   https://github.com/zopefoundation/Products.SQLAlchemyDA/pull/2/commits/876cefc15e1f417c158447bb2b9b27561f45e6e2

**Comment by icemac** [comment]
@jordic An updated PR would be nice.

**Comment by tseaver** [comment]
Superseded by #4.

**Pull request closed without merging**
